import type { Metadata } from "next";
import { Fira_Code, Lora, Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const sansRoboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const monoFiraCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

const serifLora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={`${sansRoboto.variable} ${monoFiraCode.variable} ${serifLora.variable} antialiased`}
      >
        <ThemeProvider defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
